name: Unit test

on: [push, pull_request, workflow_dispatch]

jobs:
  lint-and-test:
    name: Lint and test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node 15 so we get NPM 7
        uses: actions/setup-node@v2
        with:
          node-version: '15'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm test
