name: Unit test

on: [push, pull_request, workflow_dispatch]

jobs:
  lint-and-test:
    name: Lint and test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install npm 8
        run: npm install -g npm@8

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm test
